### ISSUE TITLE
Enable config YAML to configure logging

### ISSUE THREAD

**Issue by jtv8** [jetavator/jetavator#17]
e.g.

```
logging:
  version: 1
  formatters:
    simple: format %(asctime)s %(message)s
  handlers:
    console:
      level: DEBUG
      class: logging.StreamHandler
      formatter: simple
    console:
      level: DEBUG
      class: logging.StreamHandler
      formatter: simple
  loggers:
    jetavator:
      handlers: console
      level: DEBUG
```
